/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.gltf 
Author: ChamberSu1996 (https://sketchfab.com/chambersu1996)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modural-robot-mecha-chimera-dyan-high-poly-mesh-becc5efade0048f2bcd6f9daf934ccd7
Title: Modural Robot Mecha Chimera Dyan high-poly mesh
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/robot.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[-0.108, 0.104, 1.632]} rotation={[-2.156, 0.487, -2.017]} scale={[1, 1, 1.5]}>
            <mesh geometry={nodes.Ear_coating_white_0.geometry} material={materials.coating_white} />
            <mesh geometry={nodes.Ear_coating_black_0.geometry} material={materials.coating_black} />
          </group>
          <mesh geometry={nodes.TopCam_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.TopCam_coating_blue_0.geometry} material={materials.coating_blue} />
          <mesh geometry={nodes.TopSocket_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.TopSensor_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.TopGlass_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.GlassBottom_coating_blue_0.geometry} material={materials.coating_blue} />
          <mesh geometry={nodes.bottomGlass_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.LightEarSmall_coating_blue_0.geometry} material={materials.coating_blue} />
          <mesh geometry={nodes.Cable_metal_0.geometry} material={materials.metal} />
          <mesh geometry={nodes.AirTaker_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.AirTaker_coating_blue_0.geometry} material={materials.coating_blue} />
          <mesh geometry={nodes.GlassSide_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.EarSmall_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.TopSide_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.GlassGap_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.SideScale_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.BottomScale_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.ScaleEarA_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.ScaleEarB_coating_white_0.geometry} material={materials.coating_white} position={[-0.001, 0, 0]} />
          <mesh geometry={nodes.ScaleBottom_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.BackScale_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.SideBottom_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.JawCorner_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.BackSideCover_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.BackCover_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.BackMidCover_coating_black_0.geometry} material={materials.coating_black} />
        </group>
        <group position={[7.522, 160.106, 3.904]} rotation={[0.592, 0.024, 0.474]} scale={100}>
          <mesh geometry={nodes.CableSocket_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Cylinder006_coating_white_0.geometry} material={materials.coating_white} position={[-0.008, -0.007, 0.02]} />
          <mesh geometry={nodes.Cylinder007_coating_white_0.geometry} material={materials.coating_white} position={[-0.007, 0.007, 0.019]} />
          <mesh geometry={nodes.Cylinder008_coating_white_0.geometry} material={materials.coating_white} position={[-0.008, 0.007, -0.02]} rotation={[-3.142, 0, -Math.PI]} />
          <mesh geometry={nodes.Cylinder009_coating_white_0.geometry} material={materials.coating_white} position={[-0.007, -0.007, -0.019]} rotation={[-3.142, 0, -Math.PI]} />
          <mesh geometry={nodes.Cylinder003_coating_white_0.geometry} material={materials.coating_white} position={[-0.016, -0.014, 0.03]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cylinder004_coating_white_0.geometry} material={materials.coating_white} position={[-0.014, -0.001, 0.039]} rotation={[0, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cylinder005_coating_white_0.geometry} material={materials.coating_white} position={[-0.027, 0.013, -0.039]} rotation={[-2.392, 0.897, 2.722]} />
          <mesh geometry={nodes.Cylinder010_coating_white_0.geometry} material={materials.coating_white} position={[-0.022, 0.002, -0.031]} rotation={[-2.392, 0.897, 2.722]} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane038_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane038_coating_white_0_1.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane038_coating_white_0_2.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane038_coating_blue_0.geometry} material={materials.coating_blue} />
          <mesh geometry={nodes.Plane038_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane038_coating_black_0_1.geometry} material={materials.coating_black} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane043_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane043_coating_white_0_1.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane043_coating_white_0_2.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane043_coating_white_0_3.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane043_coating_white_0_4.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane043_coating_black_0.geometry} material={materials.coating_black} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane045_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane045_coating_white_0_1.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane045_coating_white_0_2.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane045_coating_white_0_3.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane045_coating_white_0_4.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane045_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane045_coating_blue_0.geometry} material={materials.coating_blue} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane047_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane047_coating_white_0_1.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane047_coating_white_0_2.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane047_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane047_coating_black_0_1.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane047_coating_black_0_2.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane047_coating_blue_0.geometry} material={materials.coating_blue} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane048_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane048_coating_white_0_1.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane048_coating_white_0_2.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane048_coating_white_0_3.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane048_coating_white_0_4.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane048_coating_white_0_5.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane048_coating_white_0_6.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane048_coating_blue_0.geometry} material={materials.coating_blue} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.waistMesh001_metal_0.geometry} material={materials.metal} />
          <mesh geometry={nodes.chestMesh001_metal_0.geometry} material={materials.metal} />
          <mesh geometry={nodes.Plane106_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane106_coating_black_0_1.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane106_coating_black_0_2.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane106_coating_black_0_3.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane106_coating_black_0_4.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane106_coating_black_0_5.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane106_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane106_coating_white_0_1.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane106_coating_white_0_2.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane106_coating_white_0_3.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane106_coating_white_0_4.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane106_coating_white_0_5.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane106_coating_blue_0.geometry} material={materials.coating_blue} />
          <mesh geometry={nodes.Plane042_coating_black_0.geometry} material={materials.coating_black} />
          <mesh geometry={nodes.Plane042_coating_blue_0.geometry} material={materials.coating_blue} />
          <mesh geometry={nodes.Plane042_coating_white_0.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane042_coating_white_0_1.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane042_coating_white_0_2.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane042_coating_white_0_3.geometry} material={materials.coating_white} />
          <mesh geometry={nodes.Plane042_coating_white_0_4.geometry} material={materials.coating_white} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.tightMesh001_metal_0.geometry} material={materials.metal} />
          <group position={[0, 0.003, 0]} rotation={[0.026, 0, 0]}>
            <mesh geometry={nodes.footMesh001_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.bodyLine030_coating_white_0.geometry} material={materials.coating_white} />
            <mesh geometry={nodes.bodyLine030_coating_white_0_1.geometry} material={materials.coating_white} />
            <mesh geometry={nodes.bodyLine030_coating_black_0.geometry} material={materials.coating_black} />
            <mesh geometry={nodes.bodyLine030_coating_black_0_1.geometry} material={materials.coating_black} />
            <mesh geometry={nodes.bodyLine030_coating_blue_0.geometry} material={materials.coating_blue} />
          </group>
          <mesh geometry={nodes.calfMesh001_metal_0.geometry} material={materials.metal} />
        </group>
        <mesh geometry={nodes.AirTakerSmall_coating_black_0.geometry} material={materials.coating_black} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.SideScaleArray_coating_black_0.geometry} material={materials.coating_black} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.BackTopCover_coating_white_0.geometry} material={materials.coating_white} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.upperArmMesh001_metal_0.geometry} material={materials.metal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.foreArmMesh001_metal_0.geometry} material={materials.metal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.elbowMesh001_metal_0.geometry} material={materials.metal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.hipMesh001_metal_0.geometry} material={materials.metal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.palm_metal_0.geometry} material={materials.metal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/robot.gltf')
